version: 0.2

phases:
  install:
    runtime-versions:
      golang: 1.x
    commands:
      - echo "Installing dependencies..."
      - go mod tidy
  build:
    commands:
      - echo "Building the Go app..."
      - export GOOS=linux
      - export GOARCH=amd64
      - go build -o bootstrap main.go
      - echo "Setting executable permissions for 'bootstrap'..."
      - chmod +x bootstrap
  post_build:
    commands:
      - echo "Zipping the application..."
      - zip my-todo-app.zip bootstrap test.db
      - echo "Build completed on $(date)"

artifacts:
  files:
    - my-todo-app.zip

cache:
  paths:
    - /root/.cache/go-build
