version: 0.2

env:
  variables:
    GO111MODULE: "on"

phases:
  install:
    runtime-versions:
      golang: 1.18
    commands:
      - echo "Installing dependencies..."
      - go mod tidy
  build:
    commands:
      - echo "Building the Go app..."
      - GOOS=linux GOARCH=amd64 go build -o main main.go
  post_build:
    commands:
      - echo "Zipping the application..."
      - zip my-todo-app.zip main
      - echo "Build completed on $(date)"

artifacts:
  files:
    - my-todo-app.zip

cache:
  paths:
    - /root/.cache/go-build
