version: 0.2
phases:
  install:
    runtime-versions:
      golang: 1.x
    commands:
      - echo "Installing dependencies..."
      - go mod tidy
      - echo "Installing necessary build tools..."
      - yum -y install gcc
  build:
    commands:
      - echo "Setting environment variables..."
      - export GOOS=linux GOARCH=amd64 CGO_ENABLED=1
      - echo "Building the Go app..."
      - go build -o bootstrap main.go
      - echo "Setting executable permissions for 'bootstrap'..."
      - chmod +x bootstrap
  post_build:
    commands:
      - echo "Zipping the application..."
      - zip my-todo-app.zip bootstrap test.db
      - echo "Build completed on $(date)"
artifacts:
  files:
    - my-todo-app.zip
cache:
  paths:
    - /root/.cache/go-build
