version: 0.2
phases:
  install:
    runtime-versions:
      docker: 18
    commands:
      - echo "Install docker if required."
  build:
    commands:
      - echo "Starting the Docker build process"
      - docker build -t my-todo-app .
      - docker run --name extract my-todo-app
      - docker cp extract:/app/bootstrap ./bootstrap
      - docker cp extract:/app/test.db ./test.db
      - docker rm extract
  post_build:
    commands:
      - echo "Zipping the application..."
      - zip my-todo-app.zip bootstrap test.db
artifacts:
  files:
    - my-todo-app.zip
cache:
  paths:
    - /root/.cache/go-build
