version: 0.2

phases:
  install:
    runtime-versions:
      golang: 1.x
    commands:
      - echo "Installing dependencies..."
      - go mod tidy
  build:
    commands:
      - echo "Building the Go app..."
      - GOOS=linux GOARCH=amd64 go build -o main main.go
      - echo "Giving execute permissions to 'main' and 'bootstrap'..."
      - chmod +x main
      - chmod +x bootstrap
  post_build:
    commands:
      - echo "Zipping the application..."
      - zip my-todo-app.zip my-todo-app.exe bootstrap template.yaml
      - echo "Build completed on $(date)"

artifacts:
  files:
    - my-todo-app.zip

cache:
  paths:
    - /root/.cache/go-build
