version: 0.2

env:
  variables:
    GO111MODULE: "on"
    AWS_DEFAULT_REGION: "ap-northeast-1" # 主要なAWSリージョンを設定
    AWS_LAMBDA_FUNCTION_NAME: "my-gp-app" # あなたのLambda関数名を指定
    S3_BUCKET_NAME: "my-go-app-bucket" # S3バケット名を指定
    S3_KEY: "my-todo-app.zip" # S3でのZIPファイルパスを指定

phases:
  install:
    runtime-versions:
      golang: 1.x # 自動で最新バージョンを使用します
    commands:
      - echo "Installing dependencies..."
      - go mod tidy

  build:
    commands:
      - echo "Building the Go app..."
      - GOOS=linux GOARCH=amd64 go build -o main main.go
      - echo "Giving execute permissions to 'bootstrap'..."
      - if [ -f bootstrap ]; then chmod +x bootstrap; echo "bootstrap exists and permissions set."; else echo "bootstrap does not exist."; exit 1; fi

  post_build:
    commands:
      - echo "Zipping the application..."
      - zip my-todo-app.zip main bootstrap
      - echo "Uploading to S3..."
      - aws s3 cp my-todo-app.zip s3://${S3_BUCKET_NAME}/${S3_KEY}
      - echo "Updating Lambda function..."
      - aws lambda update-function-code --function-name $AWS_LAMBDA_FUNCTION_NAME --s3-bucket $S3_BUCKET_NAME --s3-key $S3_KEY
      - echo "Build and deploy completed on $(date)"

artifacts:
  files:
    - my-todo-app.zip

cache:
  paths:
    - /root/.cache/go-build
