Resources:
  MyTodoAppFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: bootstrap
      Runtime: provided.al2
      CodeUri: ./cmd/main
      MemorySize: 128
      Timeout: 10
      Environment:
        Variables:
          DATABASE_PATH: "/tmp/test.db"
      Events:
        Api:
          Type: Api
          Properties:
            Path: /{proxy+}
            Method: ANY
